// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title AetherVoice Verification Log
 * @dev Implements a trustless settlement and logging system for AI-driven fraud detection.
 * Uses patterns from ERC-8183 for agentic commerce.
 */

contract VerificationLog {
    enum Status { Open, Funded, Submitted, Completed, Rejected, Expired }

    struct InterrogationJob {
        address client;        // The user requesting verification
        address agent;         // The AetherVoice Agent (registered via ERC-8004)
        uint256 budget;        // Payment for the interrogation (in BNB/USDC)
        bytes32 fraudReport;   // IPFS hash of the interrogation transcript and verdict
        uint8 trustScore;      // The final 0-100 score
        Status status;
    }

    mapping(uint256 => InterrogationJob) public jobs;
    uint256 public nextJobId;

    event JobCreated(uint256 jobId, address client, string description);
    event VerificationLogged(uint256 jobId, uint8 trustScore, bytes32 reportHash);
    event PaymentSettled(uint256 jobId, address agent, uint256 amount);

    /**
     * @notice Creates a new interrogation job.
     */
    function createInterrogation(address _agent, string memory _description) external returns (uint256) {
        uint256 jobId = nextJobId++;
        jobs[jobId].client = msg.sender;
        jobs[jobId].agent = _agent;
        jobs[jobId].status = Status.Open;

        emit JobCreated(jobId, msg.sender, _description);
        return jobId;
    }

    /**
     * @notice Logs the result of the AI interrogation and settles payment.
     * @param _jobId The unique ID of the verification task.
     * @param _score The 0-100 Trust Score generated by AetherVoice.
     * @param _report The IPFS hash containing the detailed "Combat Logic" findings.
     */
    function settleVerification(uint256 _jobId, uint8 _score, bytes32 _report) external {
        InterrogationJob storage job = jobs[_jobId];
        require(msg.sender == job.agent, "Only the designated agent can settle.");
        
        job.trustScore = _score;
        job.fraudReport = _report;
        job.status = Status.Completed;

        emit VerificationLogged(_jobId, _score, _report);
        emit PaymentSettled(_jobId, job.agent, job.budget);
    }
}
